In [49]:
import pandas as pd

In [50]:
df = pd.read_csv("spotify.csv")

In [51]:
df.head(10)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...
5,ABBA,Burning My Bridges,/a/abba/burning+my+bridges_20003011.html,"Well, you hoot and you holler and you make me ..."
6,ABBA,Cassandra,/a/abba/cassandra_20002811.html,Down in the street they're all singing and sho...
7,ABBA,Chiquitita,/a/abba/chiquitita_20002978.html,"Chiquitita, tell me what's wrong \r\nYou're e..."
8,ABBA,Crazy World,/a/abba/crazy+world_20003013.html,I was out with the morning sun \r\nCouldn't s...
9,ABBA,Crying Over You,/a/abba/crying+over+you_20177611.html,I'm waitin' for you baby \r\nI'm sitting all ...

In [52]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57650 entries, 0 to 57649
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  57650 non-null  object
 1   song    57650 non-null  object
 2   link    57650 non-null  object
 3   text    57650 non-null  object
dtypes: object(4)
memory usage: 1.8+ MB

In [54]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [55]:
df.describe()

,artist,song,link,text
count,57650,57650,57650,57650
unique,643,44824,57650,57494
top,Donna Summer,Have Yourself A Merry Little Christmas,/z/zwan/heartsong_20148991.html,I just came back from a lovely trip along the ...
freq,191,35,1,6

In [56]:
df.shape

(57650, 4)

In [57]:
df = df.sample(5000).drop("link", axis=1).reset_index(drop=True)

In [58]:
df

,artist,song,text
0,Lana Del Rey,I Can Fly,I Can Fly \r\nYou had me caged up like a bird...
1,Pat Benatar,I'm Gonna Follow You,"I'm gonna follow you, 'till I wear you down \..."
2,Cyndi Lauper,Cold Sky,(x) \r\nWalking down the street \r\nMemories...
3,UB40,Strange Fruit,Southern trees bear a strange fruit \r\nBlood...
4,Weezer,The First Noel,The first Noel the angel did say \r\nWas to c...
...,...,...,...
4995,Evanescence,Give Unto Me,I've been watching you from a distance \r\nTh...
4996,UB40,Dubmobile,Talking about the reel the reel the reel.... ...
4997,Gloria Estefan,I Know You Too Well,"Baby, it's nothing that you've said \r\nBut I..."
4998,Quiet Riot,We've Got The Magic,All I need is a place in my heart \r\nTo keep...
4999,Glen Campbell,Just Another Piece Of Paper,"It looked like any other piece of paper, \r\n..."

In [59]:
df['text'][0]

"I Can Fly  \r\nYou had me caged up like a bird in mid-summer  \r\nYou saw me waiting I was crazy on fire waiting to fly  \r\nI Can Fly  \r\n  \r\nI had bright wishes in the summer, I was bathing in sunlight  \r\nI was painting in the garden like a ghost in Mid-July  \r\nRunning fast from something with my eyes wide like  \r\nSaucers spinning in the sun  \r\n  \r\nI had a dream that I was fine  \r\nI wasn't crazy, I was divine  \r\n  \r\n  \r\nI Can Fly  \r\nYou had me caged up like a bird in mid-summer  \r\nYou saw me waiting I was crazy on fire waiting to fly  \r\nI Can Fly  \r\n  \r\nYour lies were hard kisses in the summer  \r\nI was dreaming of a lake  \r\nDreaming of the water where I'd rise like a Phoenix  \r\nOr that [?] from the fire  \r\nI've got things to tell you like I know that you're a liar  \r\n  \r\nI had a dream that I was fine  \r\nI wasn't crazy, I was divine  \r\n  \r\nI Can Fly  \r\nYou had me caged up like a bird in mid-summer  \r\nYou saw me waiting I was crazy on fire waiting to fly  \r\nI Can Fly  \r\n  \r\nYour words cut like a knife and butter  \r\nI was fighting for my art  \r\nFighting with my lover, you had me so tied up  \r\nThinking there's no other  \r\nYeah, right  \r\nYeah, right  \r\n  \r\nI Can Fly  \r\nYou had me caged up like a bird in mid-summer  \r\nYou saw me waiting I was crazy on fire waiting to fly  \r\nI Can Fly\r\n\r\n"

## Text Cleaning / Preprocessing

In [60]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex=True)

In [61]:
df.tail(5)

,artist,song,text
4995,Evanescence,Give Unto Me,i've been watching you from a distance \r tha...
4996,UB40,Dubmobile,talking about the reel the reel the reel.... ...
4997,Gloria Estefan,I Know You Too Well,"baby, it's nothing that you've said \r but i ..."
4998,Quiet Riot,We've Got The Magic,all i need is a place in my heart \r to keep ...
4999,Glen Campbell,Just Another Piece Of Paper,"it looked like any other piece of paper, \r b..."

In [62]:
import sys
!{sys.executable} -m pip install nltk

Requirement already satisfied: nltk in c:\glassimb\venv\lib\site-packages (3.9.2)
Requirement already satisfied: joblib in c:\glassimb\venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: click in c:\glassimb\venv\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in c:\glassimb\venv\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in c:\glassimb\venv\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\glassimb\venv\lib\site-packages (from click->nltk) (0.4.6)

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\GLASSIMB\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [63]:
import nltk
nltk.download('punkt_tab')
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [64]:
stemmer = PorterStemmer()

In [65]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a = [stemmer.stem(w) for w in token]
    return " ".join(a)

In [66]:
token("you are beautiful, beauty")

'you are beauti , beauti'

In [67]:
df['text'].apply(lambda x:token(x))

0       i can fli you had me cage up like a bird in mi...
1       i 'm gon na follow you , 'till i wear you down...
2       ( x ) walk down the street memori surround me ...
3       southern tree bear a strang fruit blood on the...
4       the first noel the angel did say wa to certain...
                              ...
4995    i 've been watch you from a distanc that dista...
4996    talk about the reel the reel the reel .... ( e...
4997    babi , it 's noth that you 've said but i know...
4998    all i need is a place in my heart to keep me h...
4999    it look like ani other piec of paper , but i t...
Name: text, Length: 5000, dtype: object

In [68]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
tfid = TfidfVectorizer(analyzer='word', stop_words='english')

In [70]:
matrix = tfid.fit_transform(df['text'])

In [71]:
similar = cosine_similarity(matrix)

In [72]:
similar[0]

array([1.        , 0.00395021, 0.00642014, ..., 0.04301922, 0.01623744,
       0.01228942])

In [76]:
df[df['song'] == 'Give Unto Me'].index[0]

np.int64(4995)

### Recommender Function

In [82]:
def recommender(song_name):
    idx = df[df['song'] == song_name].index[0]
    distance = sorted(list(enumerate(similar[idx])), reverse=True, key = lambda x:x[1])
    song = []
    for s_id in distance[1:5]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [83]:
recommender("Give Unto Me")

['Love Will Save The Day', 'Save Me', 'Beast Of Burden', 'Save My Life']

In [84]:
import pickle

In [86]:
pickle.dump(similar, open("similarity", "wb"))

In [87]:
pickle.dump(df, open("df", "wb"))

In [90]:
import pickle
pickle.dump(df, open("df.pkl", "wb"))
pickle.dump(similar, open("similarity.pkl", "wb"))